### ISSUE TITLE
IB_DESIGNABLE for CircleProgressBar Not Working

### ISSUE THREAD

**Issue by talezion** [Eclair/CircleProgressBar#10]
The IB_DESIGNABLE for CircleProgressBar not working. I am using XCode 7 and Swift 2.0. I did get it to work when adding IBInspectable to each property. See below: 

`/// @brief Width of Progress Bar
@property (nonatomic) IBInspectable CGFloat progressBarWidth;
/// @brief Progress color in Progress Bar
@property (nonatomic) IBInspectable UIColor *progressBarProgressColor;
/// @brief Track color in Progress Bar
@property (nonatomic) IBInspectable UIColor *progressBarTrackColor;
/// @brief Start Angle
@property (nonatomic) IBInspectable CGFloat startAngle;

/// @brief Whether HintView should be shown or not
@property (nonatomic) IBInspectable BOOL hintHidden;
/// @brief Inner spacing between Progress Bar and Hint View
@property (nonatomic) IBInspectable CGFloat hintViewSpacing;
/// @brief Hint View Background Color
@property (nonatomic) IBInspectable UIColor *hintViewBackgroundColor;
/// @brief Hint View Text Font
@property (nonatomic) IBInspectable UIFont *hintTextFont;
/// @brief Hint View Text Color
@property (nonatomic) IBInspectable UIColor *hintTextColor;`

**Comment by Eclair** [comment]
Tested in new environment - works. IBInspectable also available in new version. Thanks for contribution!
