### ISSUE TITLE
Start angle defaults to 90

### ISSUE THREAD

**Issue by nin-amsiq** [Eclair/CircleProgressBar#16]
It seems than the startAngle defaults to 90 degrees, and you have to set startAngle = -90 to move it to 0.

![screen shot 2016-08-02 at 08 53 43](https://cloud.githubusercontent.com/assets/12696867/17319555/b49aa9e2-588e-11e6-83b0-d8622eac7478.png)

**Comment by Eclair** [comment]
It's actually zero by normal circle coordinate system: https://www.mathsisfun.com/geometry/degrees.html

However, it's vertically mirrored due to calculation specifics.
