### ISSUE TITLE
Transparent hintViewBackgroundColor

### ISSUE THREAD

**Issue by ugochirico** [Eclair/CircleProgressBar#17]
If I set transparent (default) background color to hintViewBackgroundColor transparent bacground color I got black background.
How can I set transparent BackgroundColor to circle progress bar?

**Comment by Eclair** [comment]
Hey @ugochirico ,

I just checked out the clear color for `hintViewBackgroundColor`:

```
[_circleProgressBar setHintViewBackgroundColor:[UIColor clearColor]];
```

And it works as expected, HintView background becomes transparent. Is that what you need or you asked about something else?

Thanks,

**Comment by ugochirico** [comment]
Hi @Eclair,
many thanks. I need full transparent background. 
Thanks to your suggestions I got it by adding:

```
[_musicCircleProgressBar setHintViewBackgroundColor:[UIColor clearColor]]; 
[_musicCircleProgressBar setBackgroundColor:[UIColor clearColor]];
[_musicCircleProgressBar setProgressBarTrackColor:[UIColor clearColor]];
```

Regards,

**Comment by Eclair** [comment]
Your welcome @ugochirico , good that it helped :)
