### ISSUE TITLE
How to create two lines Inside the circle Progress Bar?

### ISSUE THREAD

**Issue by miskeen110** [Eclair/CircleProgressBar#18]
Hi,
How to create two lines inside circle progress Bar.
For Example first line contain one string and other lines contain other string.
Is it possible?

**Comment by Eclair** [comment]
Hi @miskeen110,

I believe you can easily achieve it using `\n` symbol for line break in text. For example:

```
[_circleProgressBar setHintTextGenerationBlock:^NSString *(CGFloat progress) {
  return [NSString stringWithFormat:@"Progress: %.0f \nMore Text", progress * 255];
}];
```

will result in something like:

```
Progress 39%
More Text
```

If you want to use different text style for 1st and 2nd line - I would suggest you to use `setHintAttributedGenerationBlock` with AttributedString instead.

Does it solves your problem? 

Thanks!
