### ISSUE TITLE
Add setHintAttributedStringGenerationBlock method

### ISSUE THREAD

**Issue by loicgriffie** [Eclair/CircleProgressBar#2]
Hi,

Very nice component. I'm wondering if it could be possible to add a setHintAttributedStringGenerationBlock to have attributed string for the hint instead of just plain text.

Regards,

**Comment by Eclair** [comment]
Hi @Appsido,

I like the idea, didn't think about it. Can be very useful. Do you want to develop this feature?

Kind Regards,

**Comment by loicgriffie** [comment]
Hi @Eclair,

I'll give a try ;)

**Comment by Eclair** [comment]
Sorry, had some time, decided to implement it.

**Comment by loicgriffie** [comment]
Arf... So did I. Anyway, you kept NSString in addition of NSAttributedString. I didn't since i replace NSString with NSAttributedString.

**Comment by loicgriffie** [comment]
Let us know when this is available on cocoa pods

**Comment by Eclair** [comment]
I see. I think better to keep both methods, because to set NSString usually is simpler, than generate NSAttributedString each time. 

I will update cocoapods in 5 mins and give you link )

**Comment by Eclair** [comment]
Version 0.12 is available under CocoaPods: https://cocoapods.org/pods/CircleProgressBar

**Comment by loicgriffie** [comment]
Thanks
