### ISSUE TITLE
Error with hint text generation block example

### ISSUE THREAD

**Issue by UIApplicationMain** [Eclair/CircleProgressBar#22]
```
circleProgressBar.setHintTextGenerationBlock { (progress) -> String? in
    return String.init(format: "%.0f / 255", arguments: [progress * 255])
}
```
Causes the following error:
Cannot convert value of type '([CVarArg]) -> String?' to expected argument type 'StringGenerationBlock'!

**Comment by UIApplicationMain** [comment]
I apologize, I forgot to add [ ] to the arguments.

**Comment by Eclair** [comment]
@hellojeffy No worries, glad it works! :)
