### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by pocketwod** [Eclair/CircleProgressBar#6]
Hi, 

Thanks for writing this awesome library. I had a question about the docs - you mention this method:

```
[_circleProgressBar setProgress:(CGFloat)progress animated:(BOOL)animated duration:(CGFloat)duration];
```

But it appears its not in the library. Turns out it is exactly what I need, any chance you have it or have plans to implement?

Thanks!

**Comment by pocketwod** [comment]
sorry, noticed I just needed to pull from the git not the cocoapod, sorry to bug!

**Comment by Eclair** [comment]
Hi @itjunkii,

It's strange that it isn't available in CocoaPods, I pushed new specs...

Thanks for mentioned it, I will recheck it

**Comment by Eclair** [comment]
@itjunkii,

Looks like there is a bug with duplicated symbol, that's why it was rejected by CocoaPods.

**Comment by Eclair** [comment]
Thank you @itjunkii,

I fixed the bug and sent a new spec to cocoa pods, so soon it will be available through CocoaPods.

Thanks

**Comment by pocketwod** [comment]
Nice! Thanks @Eclair, love the control!

**Comment by Eclair** [comment]
Thanks @itjunkii,

You can star it then, btw :)
